import { createHmac, timingSafeEqual } from 'node:crypto';
import { unlink } from 'node:fs/promises';
import path from 'node:path';
import { env } from '../../config/env.js';
import type { StorageAdapter } from './types.js';

// Dev/test-only adapter: uploads land on local disk, served by this same
// server, so the whole pipeline is testable without any cloud credentials.
// Upload and signed-download URLs both point at PUT/GET /uploads/:key*,
// authorized by an HMAC token over (key, expiry) — the same shape a real
// presigned S3 URL has, so swapping to the S3 adapter later changes no
// caller code.

function sign(key: string, expiresAt: number): string {
  return createHmac('sha256', env.SESSION_SECRET).update(`${key}:${expiresAt}`).digest('hex');
}

export function verifyLocalUploadToken(key: string, expiresAt: number, token: string): boolean {
  if (Date.now() > expiresAt) return false;
  const expected = sign(key, expiresAt);
  const a = Buffer.from(expected);
  const b = Buffer.from(token);
  return a.length === b.length && timingSafeEqual(a, b);
}

export function localObjectPath(key: string): string {
  // key is generated by buildObjectKey (server-side, uuid-ish segments) and
  // never taken verbatim from a client path param without validation — see
  // the uploads route's paramsSchema — so this join can't escape UPLOAD_DIR.
  return path.join(env.LOCAL_UPLOAD_DIR, key);
}

export class LocalDiskAdapter implements StorageAdapter {
  async createUploadTarget(key: string): Promise<{ uploadUrl: string; method: 'PUT' }> {
    const expiresAt = Date.now() + 5 * 60 * 1000; // 5 minutes to complete the PUT
    const token = sign(key, expiresAt);
    const uploadUrl = `${env.PUBLIC_BASE_URL}/uploads/${key}?token=${token}&expires=${expiresAt}`;
    return { uploadUrl, method: 'PUT' };
  }

  getPublicUrl(key: string): string {
    return `${env.PUBLIC_BASE_URL}/uploads/${key}`;
  }

  async getSignedDownloadUrl(key: string, ttlSeconds: number): Promise<string> {
    const expiresAt = Date.now() + ttlSeconds * 1000;
    const token = sign(key, expiresAt);
    return `${env.PUBLIC_BASE_URL}/uploads/${key}?token=${token}&expires=${expiresAt}`;
  }

  async deleteObject(key: string): Promise<void> {
    await unlink(localObjectPath(key)).catch(() => {});
  }
}
